### ISSUE TITLE
Control logging with a runtime flag

### ISSUE THREAD

**Issue by Frizlab** [Swrve/swrve-ios-sdk#128]
In almost Frameworks/SDKs, the log level can be configured at runtime rather than compile time with a compilation option.
Would you consider adding this option in the Swrve SDK?

**Comment by Sergio-Mira** [comment]
Hi @Frizlab what advantages would it give compared to the flag we have? Does your use case involve turning it on / off at runtime somehow? Thanks!

**Comment by Frizlab** [comment]
Usually yes. I have a custom logging system which enables changing logging behavior at runtime. The log system has a system of tag and I can activate a certain log level for a certain tag.
I also have a special source file which is not version controlled just for logging configuration. When I want to change the logging configuration, I only change this file.
The log levels of frameworks and SDKs are also (when possible, but you're the only one for which it is not 😉) configured in this file.

In essence, this could be done in the compilation options, however, changing just one source file only recompile that file. Changing the compilation options recompiles everything…

Furthermore you're an SDK, not a product one runs directly. If I wanted to create a static (or dynamic) library from your project and just link with this in my project, I would not be able to change the log level _at all_.

Thanks for your understanding!

**Comment by kmarcell** [comment]
With Swift Package Manager is there a way to disable logging when adding the dependency to an iOS App Target? The GCC_PREPROCESSOR_DEFINITIONS with SWRVE_DISABLE_LOGS=1 doesn't seem to work when adding to the app target while using SPM.

**Comment by Sergio-Mira** [comment]
We are adding a runtime configurable level on the next major SDK release scheduled for the next few weeks.

**Comment by Sergio-Mira** [comment]
Happy to report that the new iOS SDK 7.0.0 has runtime configuration for the logger, use:
`[SwrveLogger setLogLevel:WARNING];` to set the level wanted: https://docs.swrve.com/faqs/sdk-integration/disable-sdk-device-logging/

Let us know how it looks etc and any feedback. Will close this one but feel free to open a new issue.
