### ISSUE TITLE
Control preferredStatusBarStyle

### ISSUE THREAD

**Issue by enagorny** [Swrve/swrve-ios-sdk#161]
Some time ago you've added option to control status bar appearance with `prefersIAMStatusBarHidden`. 
Is it possible to control status bar style?

**Comment by Sergio-Mira** [comment]
Is your status bar style per view controller? We don't have any method to override the style in our view controllers so should take the root view controller style as far as I understand.

**Comment by enagorny** [comment]
Yes, we control status bar style differently in our controllers. So I think it would be good for swrve message to control status bar style. Like it controls status bar presence now.

**Comment by adam-govan** [comment]
is it currently not taking the style from the view controller you call it from?

**Comment by Sergio-Mira** [comment]
Please reopen with more details if it is still happening
