### ISSUE TITLE
The resources for SwrveConversationSDK

### ISSUE THREAD

**Issue by rdignard08** [Swrve/swrve-ios-sdk#163]
I see two issues here that I'm wondering can be addressed.  The first is that the images aren't in an xcasset which means that when this is packaged up every device will download every image in a given image set.  The second is that there are no `@3x` images for the 6+ which is good just for completeness sake.  I can write a PR for the xcasset, but I wanted to ask first if there is some reason that's not being done.

**Comment by adam-govan** [comment]
Hi @rdignard08 
Thanks for the comment, you're right, we'll look into addressing this for next release

**Comment by adam-govan** [comment]
resolved as part of release 4.6 https://github.com/Swrve/swrve-ios-sdk/releases/tag/4.6.0
