### ISSUE TITLE
make permission request for photo camera optional

### ISSUE THREAD

**Issue by kolotum** [Swrve/swrve-ios-sdk#192]
To avoid error messages coming from iTunes Connect like

"This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data."

please add a preprocessor macro SWRVE_NO_PHOTO_CAMERA as described in https://docs.swrve.com/faqs/sdk-integration/exclude-optional-ios-frameworks/ to make the camera permission request optional.

**Comment by Sergio-Mira** [comment]
Hi @kolotum thanks for opening this issue. We'll look into it!

**Comment by Sergio-Mira** [comment]
Are you currently blocked or have you added "NSCameraUsageDescription" for now?

**Comment by kolotum** [comment]
The app does not contain a NSCameraUsageDescription key for now.

I have patched the version 4.6.0 locally. It would be great if you could add the macro in the next versions so we can still use the official pod version.

**Comment by Sergio-Mira** [comment]
We'll do! Did you have to remove any frameworks apart from removing/ifdef the references to the camera code?

**Comment by kolotum** [comment]
We did not remove any framework for this issue. AVFoundation is still integrated.

only ifdef in
ISHPermissionRequest+All.m
ISHPermissionRequestPhotoCamera.h
ISHPermissionRequestPhotoCamera.m

(just like the already existing SWRVE_NO_PHOTO_LIBRARY)

**Comment by Sergio-Mira** [comment]
That is super info, thanks! We have someone working on it and it'll be part of our next release

**Comment by kolotum** [comment]
btw my list above wasn't complete. I also added ifdef in SwrvePermission (.h & .m)

**Comment by adam-govan** [comment]
This has been fixed in the latest release :)
