### ISSUE TITLE
Please make swrve compatible with Carthage

### ISSUE THREAD

**Issue by st3fan** [Swrve/swrve-ios-sdk#203]
I did not see explicit support for Carthage, which is a popular alternative to CocoaPods. It would be great if Swrve supported it.

**Comment by Sergio-Mira** [comment]
Hi @st3fan we currently don't have support to distribute our library as a framework. If we add support for it we'll look into adding it to Carthage. Thanks!

**Comment by st3fan** [comment]
I'm curious, why can't it be a framework?

**Comment by Sergio-Mira** [comment]
It can be a framework, but we don't have that distribution option at the moment unfortunately.

**Comment by KevBrodigan** [comment]
Carthage support added in release-4_11_3
