### ISSUE TITLE
Allowing users to disable push notifications

### ISSUE THREAD

**Issue by richmondwatkins** [Swrve/swrve-ios-sdk#229]
Is there an endpoint for disabling push notifications on a particular device? Ideally I'd like to be able to allow my users to toggle push notifications on and off from within the app with a switch. Is this possible?

**Comment by Sergio-Mira** [comment]
HI @richmondwatkins you could call
`[[UIApplication sharedApplication] unregisterForRemoteNotifications]`
which would invalidate the device token in Apple's servers, meaning the device would not see push notifications anymore.

We are looking at more advanced solutions and will keep this issue posted.

**Comment by Sergio-Mira** [comment]
`[[UIApplication sharedApplication] unregisterForRemoteNotifications]` is the way to go to avoid getting push notifications. Unfortunately there is no way to selectively stop a notification from showing by using an in-app configuration given how the OS works.

Another alternative could be send a silent push notification instead and display a local notification from it instead, checking first if the user has allowed notifications in the in-app setting.
