### ISSUE TITLE
Removed check for constant SWRVE_NO_PHOTO_CAMERA in version 4.8.0

### ISSUE THREAD

**Issue by kolotum** [Swrve/swrve-ios-sdk#231]
In SDK version 4.8.0 the checks for SWRVE_NO_PHOTO_CAMERA were removed. Are there any plans to re-add the logic you introduced in October 2016?

(Refer to closed issue #192 )

**Comment by Sergio-Mira** [comment]
Hi @kolotum we'll bring it back on 4.9 which is coming next!

**Comment by Sergio-Mira** [comment]
The check is back in the latest release 4.9!
