### ISSUE TITLE
UIApplication sharedApplication in app extension

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#233]
`#if !(defined(__has_feature) && __has_feature(attribute_availability_app_extension))
` is not the proper way to check if the code is running in an app extension. https://stackoverflow.com/questions/24018380/what-is-the-preprocessor-macro-to-test-whether-an-application-extension-is-being#comment48827623_29076070

See how SDWebImage handles this issue by checking if UIApplication responds to the selector sharedApplication. https://github.com/rs/SDWebImage/blob/2f892f968fe03e82f468adf9df20fd6b06254aea/SDWebImage/SDWebImageDownloaderOperation.m#L129-L144

**Comment by dominicmarmionswrve** [comment]
Thanks you @jerelevine for letting us know. If this is blocking you please say so. We'll look into this shortly and get back back to you.

**Comment by Sergio-Mira** [comment]
I just tested on iOS10 and the SDWebImage check is returning true (incorrect) as the class is there and it responds to that selector but the returning value is nil in the SE.

It is working as expected with the current code but we'll add a selector & response != nil check in the next release. Cheers!

**Comment by Sergio-Mira** [comment]
We've updated the SE check in 4.11.3 which was released last week
