### ISSUE TITLE
Can't upload app via Xcode 9 beta with Swrve

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#234]
<img width="696" alt="application-uploader-itunes-store-operation-failed" src="https://user-images.githubusercontent.com/6404082/30229682-bbaeacec-9497-11e7-99b1-c30de6392055.png">

Although the error doesn't seem to have anything to do with Swrve, when I include Swrve in the app, I receive this error when attempting to upload the app to iTunes Connect via Xcode 9. When I exclude Swrve, the app is uploaded without error.

**Comment by Sergio-Mira** [comment]
Hi @jerelevine thanks for contacting us. Do you use any other Pod? It is probably related to this bug in Cocoapods and it is tracked here: https://github.com/CocoaPods/CocoaPods/issues/7003

**Comment by jerelevine** [comment]
That fixed the problem for me. Thanks for the help!
