### ISSUE TITLE
Native SKStoreReviewController requestReview support

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#235]
I'm wondering what your plan is for native support for `[SKStoreReviewController requestReview]`?

Currently we use Swrve for a rate the app In-App message and then deep link to rate the App Store. Ideally, we'd like to be able to trigger prompting to rate the app via `[SKStoreReviewController requestReview]` natively without showing a message beforehand but still using Swrve events to trigger this at the appropriate time.

**Comment by Sergio-Mira** [comment]
Hi @jerelevine, it is something we are looking into but we don't have a release version for it. I'll keep this issue updated with any news. Thanks!

**Comment by Sergio-Mira** [comment]
You could achieve this using a Custom Button or a Deeplink and call that method.

**Comment by borisyurkevich** [comment]
@jerelevine I don't see why you couldn't use Swrve event in combination with the `requestReview` method? Just don't use wherever Swrve offers for asking user to review.
