### ISSUE TITLE
+[SwrvePermissions updatePermissionsStatusCache:] crash

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#237]
I'm getting EXC_BAD_ACCESS KERN_INVALID_ADDRESS crashes on +[SwrvePermissions updatePermissionsStatusCache:]. I believe that although adding entries to the dictionary is thread-safe via @synchonized, the way the dictionary is created isn't thread-safe.

https://github.com/Swrve/swrve-ios-sdk/blob/aaa89d977e1ef1a38e2a7ebfc539b51bd5ea3a2a/SwrveSDKCommon/Common/SwrvePermissions.m#L102-L111

**Comment by Sergio-Mira** [comment]
Thanks @jerelevine we are looking at this crash now. Do you have any more info on how to get it to crash?

**Comment by jerelevine** [comment]
Hi Sergio, I can't reproduce the crash. It seems that getNotificationSettingsWithCompletionHandler: returns on an arbitrary queue. I've attached a sample stack trace to see if that helps.

[com.credibleinc.chefsfeed_issue_1972_crash_976f26c4aac947f49ec2058d8d70c50a_f87024089e1511e784b256847afe9799_0_v2.txt](https://github.com/Swrve/swrve-ios-sdk/files/1360499/com.credibleinc.chefsfeed_issue_1972_crash_976f26c4aac947f49ec2058d8d70c50a_f87024089e1511e784b256847afe9799_0_v2.txt)

**Comment by Sergio-Mira** [comment]
Thanks for the stack trace and all the info. We've put a fix for this issue on 4.11.4 that has just been released, let us know how it goes!

**Comment by jerelevine** [comment]
Great thanks!
