### ISSUE TITLE
Dependency on SwrveConversationSDK

### ISSUE THREAD

**Issue by rdignard08** [Swrve/swrve-ios-sdk#239]
Hello!

My company currently uses the pod SwrveSDK for A/B testing, and I'm curious if there's a plan to remove the dependency on SwrveConversationSDK so that for people that don't use it, they don't have to include that code in their bundle.

**Comment by dominicmarmionswrve** [comment]
Hi there, thanks for getting in touch. There are no plans to remove this dependency so it's going to remain part of the sdk. 

Even if you don't use conversations, we don't see anything wrong with having it there ready for you to use sometime in the future if you change your mind. We have some exciting changes planned for conversations in 2018.

Why do you want to exclude it?

**Comment by rdignard08** [comment]
We're interested in reducing our code footprint and unused code and assets is an easy target.  We've had some of our other 3rd party's do this already (Firebase and Facebook), and I saw that Swrve has a similar structure to those.

**Comment by dominicmarmionswrve** [comment]
All assets, except for three tiny ones, are downloaded when conversations are loaded. The code footprint/assets from SwrveConversationSDK are so minimal that this wouldn't be worth it.
