### ISSUE TITLE
Swrve messages can cause `unrecognized selector` exception on devices running iOS 8

### ISSUE THREAD

**Issue by kaplad** [Swrve/swrve-ios-sdk#241]
`SwrveMessageViewController.m`:
```
UITapGestureRecognizer *playPress = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(buttonSelected)];
playPress.allowedPressTypes = @[[NSNumber numberWithInteger:UIPressTypePlayPause]];
[self.view addGestureRecognizer:playPress];
```
Unfortunately `setAllowedPressTypes` is only available from `iOS 9`

```
-(void)updateBounds
{
    // Update the bounds to the new screen size
    [self.view setFrame:[[UIScreen mainScreen] bounds]];
    [self.view setNeedsFocusUpdate];
    [self.view updateFocusIfNeeded];
}
```
`setNeedsFocusUpdate` and `updateFocusIfNeeded` are part of `UIFocusEnvironment` protocol which is also available only from iOS 9

`SwrveMessageController.m`
```
[messageViewController setNeedsFocusUpdate];
[messageViewController updateFocusIfNeeded];
```
Same issue as previous

**Comment by adam-govan** [comment]
Hi @kaplad Thanks for bringing this to our attention! 
I'm going to have a look into this now. I might reply again if I need any further info 👍 

one thing to note: if by chance you're also building for tvOS, our minimum supported OS version is 9

**Comment by kaplad** [comment]
@adam-govan happy to help! :) No, sorry, we only build our app for iOS

**Comment by adam-govan** [comment]
hi @kaplad 
we've just released a hotfix for this issue: https://github.com/Swrve/swrve-ios-sdk/releases/tag/5.2.1

Thanks again for letting us know 😄 👍

**Comment by kaplad** [comment]
@adam-govan awesome! thank you ;)
