### ISSUE TITLE
5.2.1 Fails to compile on Xcode 9.3 & Swift 4.1

### ISSUE THREAD

**Issue by kevmalek** [Swrve/swrve-ios-sdk#242]
The SDK fails to compile with the error: `Duplicate interface definition for class 'SwrvePush'`

Also there's the warning: `Duplicate protocol definition of 'SwrvePushResponseDelegate' is ignored`

**Comment by dpiletski** [comment]
The same issue for me. It seams like PR is already there, but not merge yet.

**Comment by MaikCL** [comment]
Same here, waiting for the merge

**Comment by bastianX6** [comment]
Same here. It's really necessary.

**Comment by xrelative** [comment]
Same here ✋

**Comment by KevBrodigan** [comment]
Hi All, this will be fixed in the next release which will be available shortly.

**Comment by KevBrodigan** [comment]
These issues have been addressed in the latest release 5.2.2
