### ISSUE TITLE
Passing launch options loses rich push action identifier

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#244]
When passing in launch options to SDK, it doesn't take into account the action identifier. So if a user taps on a rich push button and it launches the app, the user is not directed to the button's action but rather to the default action.

"checkLaunchOptionsForPushData:" calls the "remoteNotificationReceived:" received selector which doesn't take into account the action identifier. Swrve should check if UNUserNotificationCenter exists and if it is the delegate. If so, it should not call "checkLaunchOptionsForPushData:".

https://github.com/Swrve/swrve-ios-sdk/blob/17f1c96debe9798fc47ab51108c29595c6f02fb2/SwrveSDK/SDK/Swrve.m#L381-L397

**Comment by Sergio-Mira** [comment]
Hi @jerelevine thanks for letting us know. We'll investigate and fix it in a hotfix/upcoming release.

**Comment by Sergio-Mira** [comment]
Hi @jerelevine we've tried to reproduce the problem and we haven't been able to.

If you click on the whole notification the app will open and launchOptions will include a notification key. However, if you click on a button there won't be any launchOptions and the other method will execute normally without any problems.

Could you let us know how to reproduce it? Is it in an specific iOS version?
Thanks!

**Comment by Sergio-Mira** [comment]
Thanks again @jerelevine for letting us know. We still haven't been able to reproduce this problem, do you happen to have more information on how to reproduce (OS, steps)? Thanks!

**Comment by Sergio-Mira** [comment]
Closing this issue, please reopen with more information if able to reproduce. Thanks again!
