### ISSUE TITLE
Push Permission Request When Not Desired

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#246]
Push token can be requested for silent push notifications. Silent push notifications don't require user permission. This code automatically asks a user for push permission despite it not always being the desired case. This code should simply call "registerForRemoteNotifications" instead of going through the entire requesting push permissions flow.

https://github.com/Swrve/swrve-ios-sdk/blob/97f360fe03c6867803dc420a5dc87ad484541743/SwrveSDK/SDK/Messaging/SwrveMessageController.m#L207-L211

**Comment by Sergio-Mira** [comment]
Thanks @jerelevine for sharing this with us. We'll look into it and come back to you. Are you being blocked by this?

**Comment by Sergio-Mira** [comment]
A fix has been applied in iOS 6.0.1, thanks again!
