### ISSUE TITLE
[Question] Migrating from UIWebView to WKWebView

### ISSUE THREAD

**Issue by jozsef-vesza** [Swrve/swrve-ios-sdk#247]
From the [docs](https://developer.apple.com/documentation/uikit/uiwebview):
> Starting in iOS 8.0 and OS X 10.10, use WKWebView to add web content to your app. Do not use UIWebView or WebView.

Are there any plans to migrate to using `WKWebView` instead of `UIWebView` within the framework? I haven't yet checked how big this task would be, but if other things have higher priority I can try to find some time to help out.

Thanks!

**Comment by Sergio-Mira** [comment]
Hi @jozsef-vesza we want to move to WKWebView but it is not a priority at the moment. We'll keep you posted on the progress of moving to that view (easier now that we support iOS 10+) in this thread.

**Comment by KevBrodigan** [comment]
Hi @jozsef-vesza. We have migrated to WKWebView and all references to UIWebview have been removed from the SDK in version: 6.2.1
