### ISSUE TITLE
Vulnerabilities caused by use of the Weak HASH API(s)

### ISSUE THREAD

**Issue by MayankSehgal95** [Swrve/swrve-ios-sdk#249]
Hi,
We are using Version 6.1.0 in our project & since there is CC_MD5 present in code which is creating vulnerabilities in the code. So just wanted to know whether these banned API's are going to be resolved in upcoming versions.

We are looking forward to your support.
Thanks

**Comment by oisin** [comment]
Hi there -- the MD5 usage in the code is to create a digest, like a checksum, for previous text. It's not used as an encryption strategy. Thanks for your inquiry, however, if security scanning tools are flagging this as an issue we will consider replacing it in a future release.

**Comment by MayankSehgal95** [comment]
Thanks for the update. When we can expect the future release?

**Comment by oisin** [comment]
We've no set dates as yet for our next major number release.
