### ISSUE TITLE
The docs link on the README is incorrect

### ISSUE THREAD

**Issue by marcomorain** [Swrve/swrve-ios-sdk#25]
- The link to  https://dashboard.swrve.com/help/category/20127113 should link to http://docs.swrve.com/developer-documentation/37926233/
- On http://docs.swrve.com/developer-documentation/37926233/ there is some orange text that says "Integrate the iOS SDK Using CocoaPods" when you click on it it does nothing.

**Comment by Sergio-Mira** [comment]
Thanks for those Marc! Hope everything is going well on Circle CI.
We are going to improve the readme this release and will push again this year to get the builds setup there too, any plans for Windows UWP builds?
