### ISSUE TITLE
Strong Retain causing Memory leak!

### ISSUE THREAD

**Issue by dipkasyap** [Swrve/swrve-ios-sdk#251]
Setting delegate is causing Memory leak.

`@property (nonatomic, retain) id <SwrveMessageDelegate> showMessageDelegate;            /*!< Implement this delegate to intercept in-app messages. */`

**Comment by Sergio-Mira** [comment]
Hi @dipkasyap,

We have now released a new version of the Swrve iOS SDK:
https://docs.swrve.com/release-notes/sdk-release-notes/ios-sdk-release-notes/#Release_64

In this release we've moved delegates to be weak.

Let me know if you have any further questions on this.

Best,
Sergio
