### ISSUE TITLE
Swrve 6.3.0 pod was not published

### ISSUE THREAD

**Issue by lucasaue** [Swrve/swrve-ios-sdk#252]
The last version that was published in Pod is Swrve 6.2.1, but I don't wanna use this version because there are some bugs in conversation. 

This is the error message when I try to install the 6.3.0 version. When I remove the version in my Podfile, I install the latest publish version (6.2.1)

[!] CocoaPods could not find compatible versions for pod "SwrveSDK":
  In Podfile:
    SwrveSDK (= 6.3.0)

None of your spec sources contain a spec satisfying the dependency: `SwrveSDK (= 6.3.0)`.

**Comment by Sergio-Mira** [comment]
Hi @lucasaue thanks for reaching out. The SDK is published and can be visible in the Cocoapod website: https://cocoapods.org/pods/SwrveSDK

Depending on the cocoapod gem version you might need to run a "pod repo update" to be able to use it.

**Comment by lucasaue** [comment]
Thank you!
