### ISSUE TITLE
[Request] SPM support 

### ISSUE THREAD

**Issue by mikolaj92** [Swrve/swrve-ios-sdk#253]
As for now, I didn't see any information regarding SPM support.
Do you plan to support SPM or is there any information regarding that?

**Comment by mario2r** [comment]
Is there any plan to support SPM in future versions?

**Comment by sandpat** [comment]
I made an attempt on implementing SPM support. Please checkout https://github.com/sandpat/swrve-ios-sdk/ (branch: spm-support)

**Comment by adam-govan** [comment]
Our latest release (6.8.0) now supports SPM. Closing this issue now. Thanks for bringing this our attention!
