### ISSUE TITLE
RootViewController doesn't handle `unrecognized selector` exception 

### ISSUE THREAD

**Issue by popei69** [Swrve/swrve-ios-sdk#254]
Hey team,

We've recently launched an in-app message campaign at scale and we caught a lot of `unrecognized selector` exception for our used rootViewController. 

![image](https://user-images.githubusercontent.com/1432849/77738108-34908a00-704a-11ea-946b-3e9e1cb3320e.png)

When digging deeper, it seems coming around `SwrveMessageViewController`. I didn't see any usage in our main codebases but from what I read, the SDK tries to get the rootViewController and cast it in a specific type to display or dismiss the given message. That's I believe where the exception happens.

The crash happens specifically for users launching the app. I'm not sure if it's because the view isn't displayed yet, or if it's already dismissed, or in between state. It happens mostly for iOS13 but also for iOS12 devices.

The current version used is 6.3.0, I'm upgrading to 6.4.1 as well but I can see the potential failing code is still there. 

```
SwrveInAppCampaign *dismissedCampaign = ((SwrveMessageViewController*)self.inAppMessageWindow.rootViewController).message.campaign;
[dismissedCampaign messageDismissed:now];
```

Thanks

**Comment by KevBrodigan** [comment]
I believe this is related to resetting the key window root controller.

eg something like this been set: UIApplication.shared.keyWindow?.rootViewController = TabBarController()
while a Swrve IAM is showing, before been dismissed Essentially, you can’t be sure what the keyWindow is at the time that is done.

This could lead to potential issues with our SDK as we create a UIWindow to display IAMs and set it as the keyWindow. 
 
Would suggest using your own window and setting the TabBarController as its root and make it the keyWindow OR just use the root window through the app delegate 

eg UIApplication.shared.delegate.window.rootViewController = TabBarController()

**Comment by popei69** [comment]
Hey @KevBrodigan, is my pull request above still relevant for you? It got approved around same time you closed this one. If not, I'll close it as well.

**Comment by KevBrodigan** [comment]
Apologies for delay in responding, no we can close thanks
