### ISSUE TITLE
iOS 12 support

### ISSUE THREAD

**Issue by borisyurkevich** [Swrve/swrve-ios-sdk#257]
When trying to compile your SDK with iOS deployment target set to 12 it fails because you are using deprecated API for persisting files on disk. This is easy to update https://stackoverflow.com/a/53581313/1162044

<img width="943" alt="SwrveProfileManager.m" src="https://user-images.githubusercontent.com/1362354/83868127-45ccd580-a722-11ea-896c-5f6c5ee2e1b8.png">

_SwrveProfileManager_

**Comment by borisyurkevich** [comment]
Since `archivedDataWithRootObject:requiringSecureCoding:error` is available in iOS 11, I can try to update it myself, looks trivial.

**Comment by borisyurkevich** [comment]
I could patch this, but Swrve would still not compile for iOS 12 because it uses `CTTelephonyNetworkInfo.subscriberCellularProvider`, and replacement is not available in iOS 11. The iOS 12 property is `serviceSubscriberCellularProviders`. This is due to new iPhone devices which support dual SIM.

**Comment by borisyurkevich** [comment]
Here's PR, not sure how link it with this ticket: https://github.com/Swrve/swrve-ios-sdk/pull/258
I would appreciate a review, if we can update this this will ease iOS 12 transitions for many since we will only need to change Swrve code in one place.

**Comment by borisyurkevich** [comment]
I have opened another PR to resolve issue with `CTTelephonyNetworkInfo.subscriberCellularProvider` while keeping iOS 11 compatibility https://github.com/Swrve/swrve-ios-sdk/pull/259

**Comment by KevBrodigan** [comment]
@borisyurkevich Thanks for the PR's, we will be addressing the deprecations (and others) you raised in our next SDK release. Just need to ensure all deprecation are wrapped in @available checks for backwards compatibility for our min support version.

**Comment by Sergio-Mira** [comment]
Fixed in release-6_6_0, thanks @borisyurkevich !
