### ISSUE TITLE
Building using Xcode 12.5

### ISSUE THREAD

**Issue by kmarcell** [Swrve/swrve-ios-sdk#261]
**Swrve version:**
6.8.0

**Task:**
Build Swrve using Swift Package Manager

**Issue:**
Fails to build because initializer is made unavailable and using _new_ doesn't work anymore in Xcode 12.5 Beta

**Error Message:**
'new' is unavailable
SwrveSDK/include/SwrveMessageController.h:47:1: 'init' has been explicitly marked unavailable here

**Cause:**
SwrveMessageController.h

- (instancetype)init NS_UNAVAILABLE;

**Comment by KevBrodigan** [comment]
@kmarcell thanks for raising this issue, we will look into this and release an update if required.

**Comment by KevBrodigan** [comment]
@kmarcell, we have released version 6.8.1 which has removed the unavailable annotation . It should build now, thanks.

**Comment by KevBrodigan** [comment]
Fixed.
