### ISSUE TITLE
 Xcode 13 b4 - SwiftPackageManager App Extensions

### ISSUE THREAD

**Issue by mattiacantalu** [Swrve/swrve-ios-sdk#264]
Using latest version of SwrveSDK 7.0.3 and Xcode 13.0 beta 4 the App Extensions targets don't compile due:
```
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```
and
```
'openURL:' is unavailable: not available on iOS (App Extension)
```

**Comment by mattiacantalu** [comment]
Swift Packages
Resolved in Xcode 13 Beta 5

    You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)

**Comment by KevBrodigan** [comment]
Thanks @mattiacantalu for the updates on this. I'll close off this issue, as noted Apple have reversed the change on this in the latest beta.
