### ISSUE TITLE
Crash on application start from BlueDot Point SDK

### ISSUE THREAD

**Issue by darylteo** [Swrve/swrve-ios-sdk#267]
We are encountering a weird issue that seems to occur from the BDPointSDK as a direct dependency of SwrveSDK and hoping that the team here has encountered this before and can recommend a workaround as it is preventing our release. Thank you.

https://github.com/Bluedot-Innovation/PointSDK-iOS/issues/13

**Comment by davidbreenwex** [comment]
Hi @darylteo 

The Swrve SDK no longer uses BDPointSDK and hasn't for a long time so you must be on an old version of the Swrve SDK. 
The solution should be to upgrade to a more recent version.
Can you please open a support ticket by emailing support@swrve.com if you need help with this?
