### ISSUE TITLE
Apple Privacy Manifest file

### ISSUE THREAD

**Issue by mattiacantalu** [Swrve/swrve-ios-sdk#268]
Any update about the [privacy manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)?

**Comment by davidbreenwex** [comment]
Hi @mattiacantalu 

Our SDK team are currently looking into this. 
I'll update you once I know when a version of our SDK with a privacy manifest will be released. 

Best, 
David

**Comment by mattiacantalu** [comment]
https://github.com/Swrve/swrve-ios-sdk/releases/tag/8.12.0
