### ISSUE TITLE
Equivalent for dismissMessageWindow()

### ISSUE THREAD

**Issue by marekhac** [Swrve/swrve-ios-sdk#271]
Maybe it's not an issue, rather question. I try to migrate from 8.5 version to 10.0 and I can't find an equivalent for `messaging.dismissMessageWindow()` method. Can you help me ? Thanks in advance!

**Comment by KevBrodigan** [comment]
HI @marekhac 

Access directly to dismissMessageWindow was never really intended and removed in later SDKs

I would be curious to hear your use case to have access to this method?

If you are looking to hook into the dismiss actions, you can use SwrveInAppMessageDelegate, which has a callback for various button actions. See here for further info: https://docs.swrve.com/developer-documentation/integration/ios/#In-app_message_delegate_interactions

**Comment by marekhac** [comment]
@KevBrodigan now I just saw that this `dismissMessageWindow` method was never called in my project. So let's close this ticket. Thanks for detailed answer 👍
