### ISSUE TITLE
Version 4.1.0 breaks `Swrve` class compatibility

### ISSUE THREAD

**Issue by bejo** [Swrve/swrve-ios-sdk#66]
The new version, `4.1.0`, breaks `Swrve` class backwards compatibility without bumping the major version number (such an update should be labeled as `5.0.0`).

**Comment by Sergio-Mira** [comment]
Hi @bejo, could you give us more information? It should be a drop in replacement for 4.0.X

**Comment by Sergio-Mira** [comment]
It is true, the init method has changed a bit and we've moved the custom user id into the SwrveConfig object and needs to be changed when upgrading.

**Comment by bejo** [comment]
Sorry for the lack of details and yes, it is the init method that changed in `4.1.0`

**Comment by Sergio-Mira** [comment]
Hi @bejo we've just released a 4.1.1 version that brings back those methods, now marked as deprecated. We hope that blip didn't cause you much pain when upgrading. We'll be following a stricter versioning and deprecating control in the future.
Let me know if I can close this issue. Thanks!

**Comment by bejo** [comment]
That works. Thanks @Sergio-Mira! :)
