### ISSUE TITLE
Swrve Pod integrations caused, additional languages(localizations) in app store listing.

### ISSUE THREAD

**Issue by gopalAkula** [Swrve/swrve-ios-sdk#93]
Hi Team,

I got an issue while adding Swrve SDK using Pods. I submitted an app to App Store with Swrve SDK v4.0.5. By observing the build details, there are additional language support added to the build. This causes display of additional languages in app store listing. I checked the generated ipa by unzipping it. I observed some language specific files(*.lproj). Is there any way to restrict unintended language folders or it is any configuration change required?

**Comment by Sergio-Mira** [comment]
Hi @gopalAkula thanks for letting us know. We have resources in the SDK to render the in-app message text correctly in the following languages: de, en, es, fr, it, nl and pt. Do those match what you are seeing?

I believe it might be possible to remove those from the App Store after you upload your app, let me know if those match and this helps:
https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/DisplayInMoreLanguages.html

**Comment by gopalAkula** [comment]
Hi Sergio-Mira, thanks for quick reply. 
Yes we are seeing all those files while integrating Swrve SDK using cocapods. It effects the overall language support to the build. It can be observed by checking iTunes connect build details. (If you go to iTunes connect -> Activity -> Under build details. Please review attached file “itunes_build_details.png”.) It is showing Localizations with multiple languages(Dutch, English,French,…etc.). It is happening only when adding Swrve SDK to the app. Currently we are giving support only for English. Please review it in the attachment .

![itunes_build_details](https://cloud.githubusercontent.com/assets/17570796/13469406/440b1484-e0cd-11e5-912a-7b01c83cd532.png)
![itunes_localizations](https://cloud.githubusercontent.com/assets/17570796/13469405/440aff4e-e0cd-11e5-922e-13ec2ae1c110.png)

**Comment by Sergio-Mira** [comment]
We'll move to using Cocoapod resource bundles in the next SDK version, until then you could remove those with a pre_install hook like they specify here:
https://github.com/CocoaPods/CocoaPods/issues/1301

**Comment by adam-govan** [comment]
Hi @gopalAkula , we have just released iOS SDK 4.3 which fixes the issues you were seeing, it should available in Cocoapods now. Thanks!
